---
# Labels are used by Release Drafter and GitHub Labeler:
# - Determine changelog section
# - Decide if an issue/pr should be skipped
# Repository labels will be auto-configured using:
# https://github.com/marketplace/actions/github-labeler

# Type labels
- name: "breaking"
  description: "Breaking Changes"
  color: "#1d76db" # Strong blue
- name: "bug"
  description: "Something isn't working"
  color: "#d73a4a" # Red
- name: "documentation"
  description: "Improvements or additions to documentation"
  color: "#fbca04" # Yellow
- name: "enhancement"
  description: "New feature or request"
  color: "#84b6eb" # Light blue
- name: "performance"
  description: "Performance"
  color: "#b60205" # Dark red
- name: "refactoring"
  description: "Refactoring"
  color: "#f7c6c7" # Light pink
- name: "removal"
  description: "Removals and Deprecations"
  color: "#e99695" # Salmon

# Status / Workflow labels
- name: "wontfix"
  description: "This will not be worked on"
  color: "#cccccc" # Light gray
- name: "help wanted"
  description: "Extra attention is needed"
  color: "#008672" # Green
- name: "good first issue"
  description: "Good for newcomers"
  color: "#7057ff" # Purple
- name: "duplicate"
  description: "This issue or pull request already exists"
  color: "#cfd3d7" # Gray
- name: "invalid"
  description: "This issue or pull request is invalid"
  color: "#e4e669" # Yellow
- name: "question"
  description: "Further information is requested"
  color: "#d876e3" # Pink

# CI / Tests / Dependencies
- name: "tests"
  description: "Tests"
  color: "#0e8a16" # Green
- name: "ci"
  description: "Continuous Integration"
  color: "#5319e7" # Deep purple
- name: "dependencies"
  description: "Update a dependency file"
  color: "#f9d0c4" # Pastel orange

# Versioning labels
- name: "minor"
  description: "Minor version increments"
  color: "#1abc9c" # Teal
- name: "major"
  description: "Major version increments"
  color: "#e67e22" # Orange
