---
###########################################
# These are the rules used for            #
# linting all the yaml files in the stack #
# NOTE:                                   #
# You can disable line with:              #
# # yamllint disable-line                 #
###########################################
extends: default
rules:
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1

  comments:
    require-starting-space: true
    min-spaces-from-content: 1 # Used to follow prettier standard: https://github.com/prettier/prettier/pull/10926

  comments-indentation: disable

  document-start:
    present: true
    level: warning

  indentation:
    spaces: 2
    indent-sequences: consistent

  line-length:
    max: 120
    level: warning
    allow-non-breakable-words: true # URLs and long hashes will not fail CI

  new-lines:
    level: warning
    type: unix

  empty-lines:
    max: 1
    max-start: 0
    max-end: 0

  truthy:
    allowed-values:
      - "true"
      - "false"
    check-keys: true
